/** Run with Playwright available, or set PLAYWRIGHT_MODULE to its installed module path.
 * node driftops3d/tests/evidence-ui.mjs http://127.0.0.1:8765
 * CHROME_PATH can select Chrome. SCREENSHOT_DIR must be an existing absolute folder.
 */
import assert from 'node:assert/strict';
import { createRequire } from 'node:module';
const require = createRequire(import.meta.url);
const { chromium } = require(process.env.PLAYWRIGHT_MODULE || 'playwright');
const base = process.argv[2] || 'http://127.0.0.1:8765';
const browser = await chromium.launch({ executablePath: process.env.CHROME_PATH || undefined, headless: true, args: ['--no-sandbox'] });
const page = await browser.newPage();
const errors = [];
page.on('pageerror', error => errors.push(error.message));
const ready = () => page.waitForFunction(() => window.driftops?.state.site && !window.driftops.state.twinScanning, { timeout: 60000 });
try {
  for (const [width, height] of [[390,844], [768,1024], [1440,900], [2560,1440]]) {
    await page.setViewportSize({ width, height });
    await page.goto(`${base}/#/evidence/hdd-rising`);
    await page.waitForSelector('.raw-chart', { timeout: 60000 });
    assert.equal(await page.locator('.raw-chart svg[role="img"]').count(), 4);
    assert.match(await page.locator('.model-answer blockquote').innerText(), /smart_197_raw: rising/);
    assert.ok(await page.locator('.brand-name').isVisible());
    assert.ok(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth));
    assert.ok(await page.locator('#analyzeBtn').isHidden());
    await page.evaluate(() => { window.testStatusNode = document.getElementById('viewStatus'); });
    await page.locator('.case-tabs a').filter({ hasText: 'Model mismatch' }).focus();
    await page.keyboard.press('Enter');
    await page.waitForSelector('.reference.mismatch');
    assert.ok(await page.evaluate(() => document.activeElement.matches('.case-tabs [aria-current="page"]')));
    assert.ok(await page.evaluate(() => window.testStatusNode === document.getElementById('viewStatus')));
    assert.match(await page.locator('#viewStatus').innerText(), /Model mismatch loaded/);
    assert.ok(await page.locator('.chart-dates').first().evaluate(el => parseFloat(getComputedStyle(el).fontSize) >= 12));
    assert.ok(await page.locator('.chart-values').first().evaluate(el => parseFloat(getComputedStyle(el).fontSize) >= 12));
    assert.match(await page.locator('.model-answer blockquote').innerText(), /smart_194_raw: falling/);
    assert.match(await page.locator('.reference.mismatch').innerText(), /fluctuating without a clear net trend/);
    if (process.env.SCREENSHOT_DIR) await page.screenshot({ path: `${process.env.SCREENSHOT_DIR}/canary-evidence-${width}.png` });
    await page.goto(`${base}/#/site/hq`);
    await ready();
    const button = await page.locator('#analyzeBtn').boundingBox();
    assert.ok(button && button.height >= 44 && button.x >= 0 && button.x + button.width <= width, `Analyze stays in view at ${width}`);
    assert.ok((await page.locator('.brand').boundingBox()).height >= 44);
    assert.ok((await page.locator('#originBanner a').boundingBox()).height >= 44);
    if (width === 390) {
      await page.locator('#cpInput').fill('Status of HQ?');
      await page.locator('#cpInput').press('Enter');
      await page.locator('#cpLog .answer-date').waitFor();
      const log = await page.locator('#cpLog').evaluate(el => ({ height: el.clientHeight, content: el.scrollHeight, padding: parseFloat(getComputedStyle(el).paddingTop) + parseFloat(getComputedStyle(el).paddingBottom) }));
      assert.ok(log.height - log.padding >= 180, 'Mobile copilot reserves readable answer height');
      assert.match(await page.locator('#cpLog').innerText(), /Illustrative rules/);
      await page.locator('#cpLog').scrollIntoViewIfNeeded();
      if (process.env.SCREENSHOT_DIR) await page.screenshot({path: `${process.env.SCREENSHOT_DIR}/canary-copilot-answer-mobile.png`});
    }
    await page.waitForFunction(() => window.driftops.timeline?.data);
    await page.evaluate(() => window.driftops.timeline.setDay(-7));
    assert.ok(await page.locator('#cpInput').isDisabled());
    assert.ok(await page.locator('.cp-cutoff').isVisible());
    assert.ok(await page.locator('#cpLog').isHidden());
    await page.getByRole('button', { name: 'Return to Now' }).click();
    assert.ok(await page.locator('#cpInput').isEnabled());
    await page.evaluate(() => window.driftops.timeline.setDay(3));
    assert.ok(await page.locator('#cpInput').isDisabled());
    await page.getByRole('button', { name: 'Return to Now' }).click();
    await page.getByRole('link', { name: 'Evidence', exact: true }).focus();
    await page.keyboard.press('Enter');
    await page.waitForSelector('.raw-chart');
    assert.ok(await page.locator('#analyzeBtn').isHidden());
    console.log(`PASS: evidence, mismatch, Analyze bounds, and cutoff controls at ${width}x${height}`);
  }
  await page.goto(`${base}/#/site/site-a`);
  await ready();
  await page.locator('#sidebar [data-rack-pattern]').first().focus();
  await page.keyboard.press('Enter');
  await page.waitForFunction(() => window.driftops.state.rackId && document.activeElement.matches('#sidebar [data-open]'));
  await page.evaluate(() => window.driftops.timeline.setDay(-1));
  assert.ok(await page.evaluate(() => document.activeElement.matches('#sidebar [data-open]')));
  await page.evaluate(() => window.driftops.timeline.setDay(0));
  console.log('PASS: keyboard rack navigation and replay retain meaningful sidebar focus');
  await page.route('**/api/cases' , route => route.fulfill({ status: 503, contentType: 'application/json', body: JSON.stringify({error:'Saved evidence source unavailable'}) }));
  await page.goto(`${base}/#/evidence/hdd-rising`);
  await page.reload();
  await page.getByRole('button', {name:'Retry saved evidence'}).waitFor();
  assert.match(await page.locator('#evidenceView [role="alert"]').innerText(), /unavailable/);
  await page.unroute('**/api/cases');
  await page.getByRole('button', {name:'Retry saved evidence'}).click();
  await page.waitForSelector('.raw-chart');
  assert.equal(await page.locator('.raw-chart').count(), 4);
  console.log('PASS: failed evidence request recovers with Retry on the same route');
  await page.emulateMedia({ reducedMotion: 'reduce' });
  await page.setViewportSize({ width:390, height:844 });
  await page.goto(`${base}/#/site/hq`);
  await ready();
  const id = await page.evaluate(() => window.driftops.state.site.racks[0].devices[0].id);
  await page.evaluate(id => window.driftops.openDevice(id), id);
  await page.waitForFunction(() => window.driftops.state.view === 'device');
  await page.locator('#analyzeBtn').click();
  await page.waitForFunction(() => window.driftops.state.analysis && !window.driftops.state.scanning, {timeout:10000});
  await page.locator('#overview button.item').first().click();
  assert.ok(await page.locator('#panel').isVisible());
  assert.ok(await page.locator('#labels').evaluate(el => getComputedStyle(el).visibility === 'hidden'));
  assert.equal(await page.locator('#panel').getAttribute('aria-modal'), 'true');
  assert.ok(await page.locator('.topbar').evaluate(el => el.inert));
  assert.ok(await page.locator('#stage').evaluate(el => el.inert));
  assert.ok(await page.locator('#toast').isHidden());
  const hash = await page.evaluate(() => location.hash);
  const evidenceLink = await page.locator('.tabs [data-tab="evidence"]').boundingBox();
  await page.mouse.click(evidenceLink.x + evidenceLink.width / 2, evidenceLink.y + evidenceLink.height / 2);
  assert.equal(await page.evaluate(() => location.hash), hash, 'Modal background rejects pointer navigation');
  await page.locator('#panel [data-sim="1"]').focus();
  await page.keyboard.press('Enter');
  assert.ok(await page.evaluate(() => document.activeElement.matches('#panel [data-sim="1"]')));
  await page.locator('#panel .close').focus();
  await page.keyboard.press('Shift+Tab');
  assert.ok(await page.evaluate(() => document.querySelector('#panel').contains(document.activeElement)));
  await page.keyboard.press('Escape');
  assert.ok(await page.locator('#panel').isHidden());
  assert.ok(await page.locator('.topbar').evaluate(el => !el.inert));
  assert.ok(await page.locator('#stage').evaluate(el => !el.inert));
  await page.waitForFunction(() => document.activeElement.matches('#overview button.item'));
  console.log('PASS: reduced-motion analysis, mobile drawer focus, Escape, and focus return');
  assert.deepEqual(errors, []);
  console.log('PASS: no browser exceptions');
} finally { await browser.close(); }
